# Uncomment the next line to define a global platform for your project
#use_frameworks!

platform :ios, '10.0'

workspace 'EaseIMKit.xcworkspace'


#target 'EaseIM' do
 # platform :ios, '10.0'
#pod 'HyphenateChat'
#pod 'MJRefresh'
#pod 'MBProgressHUD'
#pod 'Masonry'
#project '../../EaseIM/EaseIM/EaseIM.xcodeproj'
#end

target 'EaseIMKitDemo' do
  platform :ios, '10.0'
  pod 'HyphenateChat'
  pod 'Masonry'
  project '../EaseIMKitDemo/EaseIMKitDemo.xcodeproj'
end

target 'EaseIMKit' do
  project './EaseIMKit.xcodeproj'
  pod 'HyphenateChat'
  pod 'EMVoiceConvert', '~> 0.1.0'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "UV248C5Y9N"
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
         end
    end
  end
end

